import org.jetbrains.kotlin.gradle.dsl.JvmTarget

buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath libs.kotlin.gradlePlugin
		classpath libs.kotlin.serializationPlugin
	}
}

apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'

apply plugin: 'application'
application {
	mainClass = 'com.jakewharton.dumbo.Main'
}

java {
	sourceCompatibility JavaVersion.VERSION_11
	targetCompatibility JavaVersion.VERSION_11
}

kotlin {
	compilerOptions {
		jvmTarget.set(JvmTarget.JVM_11)
	}
}

dependencies {
	implementation libs.clikt
	implementation libs.retrofit.core
	implementation libs.retrofit.converter.kotlinxSerialization
	implementation libs.okhttp.core
	implementation libs.okhttp.loggingInterceptor
	implementation 'org.jetbrains.kotlin:kotlin-reflect'
	implementation libs.kotlinx.serialization.core
	implementation libs.kotlinx.serialization.json
	implementation libs.kotlinx.serialization.json.okio
	implementation libs.kotlinx.coroutines.core
	implementation libs.okio
	implementation libs.jsoup
	implementation libs.tomlkt
	implementation libs.tika.core

	testImplementation libs.junit
	testImplementation libs.assertk
}

repositories {
	mavenCentral()
}

tasks.named('distTar').configure { task ->
	task.enabled = false
}
tasks.named('assemble').configure { task ->
	task.dependsOn(tasks.named('installDist'))
}
